name: validator_generator
description: Automatically generate code for creating validator class annotating Dart classes.
repository: https://github.com/nandanurseptama/validator_generator.dart/tree/master/validator_generator
version: 1.0.0-alpha
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.0.0

topics:
 - validator
 - class-validator
 - build-runner
 - validator-generator
 - codegen
# Add regular dependencies here.
dependencies:
  analyzer: '>=5.12.0 <7.0.0'
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.4.0
  validator_annotation: ^1.0.0-alpha
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  dart_flutter_team_lints: ^2.0.0
  lints: ^2.0.0
  path: ^1.9.0
  source_gen_test: ^1.0.6
  test: ^1.21.0

dependency_overrides:
  meta: ^1.9.0
  validator_annotation:
    path: ../validator_annotation