name: validator_annotation_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0-alpha
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0
topics:
 - validator
 - class-validator
 - build-runner
 - validator-generator
 - codegen
# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  source_gen: ^1.4.0
  validator_annotation:
    path: ../validator_annotation
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  dart_flutter_team_lints: ^2.0.0
  lints: ^2.0.0
  path: ^1.9.0
  source_gen_test: ^1.0.6
  test: ^1.21.0
