# See https://github.com/google/mono_repo.dart for details
sdk:
- pubspec
- dev

stages:
- analyze_format:
  - analyze: --fatal-infos .
    sdk:
    - pubspec
  - format:
    sdk:
    - dev

- unit_test:
  - group:
      - test
    os:
    - linux
    - windows

cache:
  directories:
  - .dart_tool/build