name: validator_annotation
description: A validator annotation for class. It will make easier for you to validate your model or DTO.
repository: https://github.com/nandanurseptama/validator_generator.dart/tree/master/validator_annotation
version: 1.0.1-alpha
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.0.0
topics:
 - validator
 - class-validator
 - build-runner
 - validator-generator
 - codegen

# Add regular dependencies here.
dependencies:
  meta: ^1.9.1

dev_dependencies:
  coverage: ^1.7.1
  dart_flutter_team_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
